on:
  push

name: JIRA Cloud Using Curl

jobs:
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Run Serenity Test
        run: mvn test verify
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /target/site