on:
  push

name: Test Evidence for Control Automation

jobs: 
  my-job:
    name: My Job
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v2
      
      - name: Run Serenity Test
        run: mvn test verify
      
      - name: Upload Test Report
        uses: actions/upload-artifact@v2
        with:
          name: test-report
          path: /home/runner/work/serenitydemo/serenitydemo/target/site/serenity/index.html

      - name: Convert to PDF
        uses: fifsky/html-to-pdf-action@master
        with:
          htmlFile: /home/runner/work/serenitydemo/serenitydemo/target/site
          outputFile: /home/runner/work/serenitydemo/serenitydemo/target/site/serenity/testreport.pdf
          pdfOptions: '{"format": "A4", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'

      - name: Upload Test PDF
        uses: actions/upload-artifact@v2
        with:
          name: test-report-pdf
          path: /home/runner/work/serenitydemo/serenitydemo/target/site/serenity/testreport.pdf